import Head from "next/head";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import HomeCreator from "../components/HomePage";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  const router = useRouter();
  const { alert } = router.query;
  const [showAlert, setShowAlert] = useState(false);

  useEffect(() => {
    if (alert === "need_review") {
      setShowAlert(true);
    }
  }, [alert]);

  return (
    <>
      <Head>
        <title>Middlebury Dorms</title>
        {/* <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        {showAlert && (
          <div className={styles.alert}>
            You need to write at least one review to access other reviews!
            <button
              onClick={() => setShowAlert(false)}
              className={styles.closeButton}
              aria-label="Close alert"
            >
              ×
            </button>
          </div>
        )}
        <HomeCreator />
        <footer className={styles.footer}>
          {/* footer if applicable later*/}
        </footer>
      </div>
    </>
  );
}
